name: Update Leaderboard

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *' # Runs everyday

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt || echo "No dependencies"

    - name: Run Leaderboard Update Script
      run: |
        python scripts/update_leaderboard.py

    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Automated leaderboard update" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
